function a=aaa(t,nu,alpha,beta,tauone,tautwo,T,kone,ktwo,lone,ltwo);

a=fone(t,nu,kone,ktwo,lone,ltwo,T,tauone,tautwo).*(ftwo(beta,lone,T)-ftwo(alpha,lone,T))...
+fone(t,nu,kone,ktwo,ltwo,lone,T,tauone,tautwo).*(ftwo(beta,ltwo,T)-ftwo(alpha,ltwo,T))-...
fthree(t,nu,kone,ktwo,lone,ltwo,T,tauone,tautwo,alpha)+...
fthree(t,nu,kone,ktwo,lone,ltwo,T,tauone,tautwo,beta);

