function a=aat(t,nu,alpha,beta,tauone,tautwo,T,kone,ktwo,lone,ltwo);

a=phione(t,nu,kone,ktwo,lone,ltwo,T,tauone,tautwo).*(ftwo(beta,lone,T)-ftwo(alpha,lone,T))...
+phione(t,nu,kone,ktwo,ltwo,lone,T,tauone,tautwo).*(ftwo(beta,ltwo,T)-ftwo(alpha,ltwo,T))-...
phithree(t,nu,kone,ktwo,lone,ltwo,T,tauone,tautwo,alpha)+...
phithree(t,nu,kone,ktwo,lone,ltwo,T,tauone,tautwo,beta);

