strbot=[...
'\nu=',num2str(nu),...
', \alpha=',num2str(alpha),...
', \beta=',num2str(beta),...
', \tau_{LGN} =',num2str(T),...
', \sigma_{LGN}=',num2str(sigma),...
', \tau_E=',num2str(taue),...
', \sigma_E=',num2str(ae),...
', \tau_I=',num2str(taui),...
', \sigma_I=',num2str(ai),...
', s_{EE}=',num2str(see),...%', s_{EI}=',num2str(sei),...
', s_{IE}=',num2str(sie),...%', s_{II}=',num2str(sii)...
];
n=1:N;
r=1:N;
figure(10)
plot(paramt(n),bote(n),'k','LineWidth',2);
hold
plot(paramt(r),boti(r),'k --','LineWidth',2);
xlabel(blapar);
ylabel('[{\it M}({\it t}_{min},\theta_{min})-{\it M}({\it t}_{min},\pi/2)]/{\it M}_{max}')
title({strtop,strmed,strbot});

hold off